---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kboom-sa  
  namespace: kboom
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kboom-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kboom-sa
  namespace: kboom